version: "3"

services:
  app:
    networks:
      - global
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    environment:
      - FLASK_DEBUG=1
    volumes:
      - ./project:/app:rw
    restart: unless-stopped
networks:
  global:
